public enum Action {
    TRANSPORTER_CREATED,
    TRANSPORTER_TRAVEL,
    TRANSPORTER_TAKE_INGOT,
    TRANSPORTER_DROP_INGOT,
    TRANSPORTER_STOPPED,
    SMELTER_CREATED,
    SMELTER_STARTED,
    SMELTER_FINISHED,
    SMELTER_STOPPED,
    CONSTRUCTOR_CREATED,
    CONSTRUCTOR_STARTED,
    CONSTRUCTOR_FINISHED,
    CONSTRUCTOR_STOPPED;
}
